<script language="javascript" type="text/javascript" src="<?php echo myURL ?>/js/import/Import.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo myURL ?>/js/import/SloManager.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo myURL ?>/js/import/Slo.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo myURL ?>/js/import/ContainerFile.js"></script>
<script type="text/javascript">
    Layout = MainMenu.getLayoutContent();
    MainMenu.MarbleLayoutText('import');
    ImportPanel(Layout);
</script>