<script language="javascript" type="text/javascript" src="<?php echo myURL ?>/js/import/Slo.js"></script>
<script language="javascript" type="text/javascript" src="<?php echo myURL ?>/js/import/SloManager.js"></script>
<script type="text/javascript">
    Layout = MainMenu.getLayoutContent();
    MainMenu.MarbleLayoutText('import');
    ImportEditPanel(Layout,<?php echo $this->id ?>);
</script>